repositories:
  - name: bitnami
    url: https://mirror.yandex.ru/helm/charts.bitnami.com

releases:
  - name: inner-circle-documents-ui
    labels:
      app: inner-circle-documents-ui
    wait: true
    chart: bitnami/aspnet-core
    version: 4.4.7
    values:
      - values.yaml
      - image:
          tag: "{{ .StateValues.image.tag }}"
      - ingress:
          hostname: "{{ .StateValues.ingress.hostname }}"
      - extraConfigMapEnvVars:
          API_ROOT_URL: "{{ .StateValues.extraConfigMapEnvVars.API_ROOT_URL }}"
          AUTH_API_ROOT_URL: "{{ .StateValues.extraConfigMapEnvVars.AUTH_API_ROOT_URL }}"
